version: '3'

services:
  engine_ChatGuru:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: engine_ChatGuru
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./src/pages:/app/src/pages
      - ./src/components:/app/src/components
      - ./public:/app/public/
      - ./lib:/app/lib/
      - ./styles:/app/styles/
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh/
      - ./next.config.js:/app/next.config.js/
      - ./.next:/app/.next/
      - ./.env:/app/.env/
